import { Shadows_Into_Light } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const shadow = Shadows_Into_Light({ subsets: ['latin'], weight: ['400']})

export const metadata = {
  title: 'ECommerce Web Application',
  description: 'Generated by baby_Dev',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={shadow.className}>{children}
      <Navbar />
      <div className='min-h-screen'>

      {children}
      </div>

      <Footer />
      </body>
    </html>
  )
}
