import { Shadows_Into_Light } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import Navbar2 from './components/Navbar2'

const shadow = Shadows_Into_Light({ subsets: ['latin'], weight: ['400']})

export const metadata = {
  title: 'ECommerce Web Application',
  description: 'Generated by baby_Dev',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={shadow.className}>
      <Navbar />
      <Navbar2 />
      <div className='min-h-screen relative top-36 -z-[1]'>
      {children}
      </div>
      <Footer />
      </body>
    </html>
  )
}
